import zerorpc

c = zerorpc.Client()
c.connect("tcp://127.0.0.1:4242")

try:
    c.bad()
except Exception as e:
    print("An error occurred: %s" % e)
